// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "zoluxiones",
    "version": "1"
  },
  "paths": {
    "/get-people-swapi": {
      "get": {
        "summary": "getPeopleSwapi",
        "description": "",
        "operationId": "getPeopleSwapi.get.get-people-swapi",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/get-planet-swapi": {
      "get": {
        "summary": "getPlanetSwapi",
        "description": "",
        "operationId": "getPlanetSwapi.get.get-planet-swapi",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/add-people": {
      "post": {
        "summary": "addPeople",
        "description": "",
        "operationId": "addPeople.post.add-people",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/get-people": {
      "get": {
        "summary": "getPeople",
        "description": "",
        "operationId": "getPeople.get.get-people",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/get-person": {
      "get": {
        "summary": "getPerson",
        "description": "",
        "operationId": "getPerson.get.get-person",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    }
  },
  "definitions": {},
  "securityDefinitions": {}
};